Add Ship.Thrusters
X-12/andromeda pull request #151
Opened 2017-11-25 21:19 UTC by jextrevor

Fixes #150.

2017-11-26 02:55 UTC, jextrevor commented
There was actually one more step needed to fix the bug, and I've fixed another bug in course.js

2017-11-26 03:17 UTC, DakotaHarward approved these changes

2017-11-27 16:45 UTC, caydenlund requested changes
Remove test variables

2017-11-27 16:55 UTC, caydenlund approved these changes

2017-11-27 16:57 UTC, merged